#$ -q UI,TELOMER
#$ -r y
#$ -cwd
#$ -j y
#$ -pe smp 32
#$ -l datacenter=LC

module unload jdk
module load openjdk/11.0.2

#Input the repository, download ID, and a final location for the processed sample
repository="collab"
manifestID="cc3dd679-e7ff-43a0-9298-77f1b77f3c01"
finalLocation="~\/workspace\/trial2"

#Input the name of the bamfile from the download (found on ICGC repository webpage for the sample)
bamin="/nfsscratch/twarowski/brca/43ea36de-f1af-41f6-ad69-cfafe7217dcb/5821de1459786ee804884db0a257bf72_gdc_realn.bam"
#Input a name for the project directory (usually donor ID and sample type, e.g. DONORID_T for tumor).
pdir="5821de1459786ee804884db0a257bf72"

####################################################################################################

outDir="."

./ICGCdownload.sh $repository $manifestID $outDir

fastqout_UM="${bamin%.bam}.UM.fq"
bamout_UM="$pdir.UM.bam"

fastqout_idsc="${bamin%.bam}.idsc.fq"
bamout_idsc="$pdir.idsc.bam"

./getUnaligned.sh $bamin $bamout_UM $fastqout_UM
./getInDels.sh $bamin $bamout_idsc $fastqout_idsc

fastqout2="$pdir.fq"
cat $fastqout_UM $fastqout_idsc > $fastqout2

mkdir $pdir
mv $fastqout2 $pdir

r1="$pdir/$fastqout2"
o1="$r1.pp"
o2="${o1%.f*}.PP.fq"
#all filtering commands are below. Can add to or change this section as needed.
java -jar ~/bin/trimmomatic-0.39.jar SE -threads 32 -phred33 ${r1} ${o1} ILLUMINACLIP:TruSeq3-PE-2.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
prinseq++ -threads 32 -fastq ${o1} -lc_dust=0.07 -out_good $o2 -out_bad /dev/null

o3="${o2%.PP.fq}.PPh.fq"
./changeFastqHeader.sh $o2 $o3

#clean up 1
rm -r $o2
rm -r $o1
rm -r $r1

mv $pdir $finalLocation

#Count reads
echo $bamin >> counts.txt
samtools view -c -@ 32 $bamin >> counts.txt
echo $bamout_UM >> counts.txt
samtools view -c -@ 32 $bamout_UM >> counts.txt
echo $bamout_idsc >> counts.txt
samtools view -c -@32 $bamout_idsc >> counts.txt

clean up 2
#rm $bamin
rm $bamout_UM
rm $bamout_idsc
