#$ -q BIOLOGY,TELOMER,UI
#$ -pe smp 32
#$ -cwd
#$ -r y
#$ -j y
# -o /dev/null
#$ -l datacenter=LC


#Change if your sample directory is located somewhere elese.


sd="~/A12"
r1="/Users/twarowski/A12/A12_CSFP200004815-1a_H5VGWDSXY_L2_R1.fq.gz"
r2="/Users/twarowski/A12/A12_CSFP200004815-1a_H5VGWDSXY_L2_R2.fq.gz"
o1=""
o2=""

#sd="SRR4047720"
#r1="$sd/SRR4047715_R1.fq"
#r2="$sd/SRR4047715_R2.fq"

#This is where you should put your sample directory folder. In that sample folder there should be a subdirectory for each Lane of sequencing.
#Paired reads need to have "R1" and "R2" in the file name just before the extension (.fq.gz).
#Loop will enter all subdirectories and process all reads files. If all lanes are from the same sample, you will need to concatinate them after.

for l in ${sd}/*
do
        if [ -d "${l}" ];then
                for f in ${l}/*
                do
                        if [[ "${f}" == *R1* ]];then
                                r1=${f}
                        elif [[ "${f}" == *R2* ]];then
                                r2=${f}
                        fi
                done
        elif [ -f "${l}" ];then
                if [[ "${l}" == *R1* ]];then
                        r1=${l}
                elif [[ "${l}" == *R2* ]];then
                        r2=${l}
                fi
	fi
done

o1="${r1%R*}1.fq"
o2="${r2%R*}2.fq"
#all filtering commands are below. Can add to or change this section as needed.
java -jar ~/bin/trimmomatic-0.39.jar PE -threads 32 -phred33 ${r1} ${r2} ${o1} ${o1}.upo ${o2} ${o2}.upo ILLUMINACLIP:TruSeq3-PE-2.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
cat ${o1} ${o1}.upo ${o2} ${o2}.upo >> ${l}temp.dust.fq
echo "writing final file to ${o1%1*}.fq"
prinseq++ -threads 32 -fastq ${l}temp.dust.fq -lc_dust=0.07 -out_good ${o1%1*}.fq -out_bad /dev/null

o3="${o1%1*}.fq"
o4="${o1%1*}pp.fq"
./changeFastqHeader.sh $o3 $o4

if [ -f "$o4" ]; then
	rm ${l}temp.dust.fq
	rm ${o1} ${o1}.upo ${o2} ${o2}.upo ${o3}
fi
#
