cd $1
echo "Commons:"
grep Inv chr1/commons_fromAll.txt | wc -l
grep Inv chr2/commons_fromAll.txt | wc -l
grep Inv chr3/commons_fromAll.txt | wc -l
grep Inv chr4/commons_fromAll.txt | wc -l
grep Inv chr5/commons_fromAll.txt | wc -l
grep Inv chr6/commons_fromAll.txt | wc -l
grep Inv chr7/commons_fromAll.txt | wc -l
grep Inv chr8/commons_fromAll.txt | wc -l
grep Inv chr9/commons_fromAll.txt | wc -l
grep Inv chr10/commons_fromAll.txt | wc -l
grep Inv chr11/commons_fromAll.txt | wc -l
grep Inv chr12/commons_fromAll.txt | wc -l
grep Inv chr13/commons_fromAll.txt | wc -l
grep Inv chr14/commons_fromAll.txt | wc -l
grep Inv chr15/commons_fromAll.txt | wc -l
grep Inv chr16/commons_fromAll.txt | wc -l
grep Inv chr17/commons_fromAll.txt | wc -l
grep Inv chr18/commons_fromAll.txt | wc -l
grep Inv chr19/commons_fromAll.txt | wc -l
grep Inv chr20/commons_fromAll.txt | wc -l
grep Inv chr21/commons_fromAll.txt | wc -l
grep Inv chr22/commons_fromAll.txt | wc -l
grep Inv chr23/commons_fromAll.txt | wc -l
grep Inv chr24/commons_fromAll.txt | wc -l
grep Inv chr25/commons_fromAll.txt | wc -l

echo "Non-Commons:"
grep Inv chr1/non_commons_fromAll.txt | wc -l
grep Inv chr2/non_commons_fromAll.txt | wc -l
grep Inv chr3/non_commons_fromAll.txt | wc -l
grep Inv chr4/non_commons_fromAll.txt | wc -l
grep Inv chr5/non_commons_fromAll.txt | wc -l
grep Inv chr6/non_commons_fromAll.txt | wc -l
grep Inv chr7/non_commons_fromAll.txt | wc -l
grep Inv chr8/non_commons_fromAll.txt | wc -l
grep Inv chr9/non_commons_fromAll.txt | wc -l
grep Inv chr10/non_commons_fromAll.txt | wc -l
grep Inv chr11/non_commons_fromAll.txt | wc -l
grep Inv chr12/non_commons_fromAll.txt | wc -l
grep Inv chr13/non_commons_fromAll.txt | wc -l
grep Inv chr14/non_commons_fromAll.txt | wc -l
grep Inv chr15/non_commons_fromAll.txt | wc -l
grep Inv chr16/non_commons_fromAll.txt | wc -l
grep Inv chr17/non_commons_fromAll.txt | wc -l
grep Inv chr18/non_commons_fromAll.txt | wc -l
grep Inv chr19/non_commons_fromAll.txt | wc -l
grep Inv chr20/non_commons_fromAll.txt | wc -l
grep Inv chr21/non_commons_fromAll.txt | wc -l
grep Inv chr22/non_commons_fromAll.txt | wc -l
grep Inv chr23/non_commons_fromAll.txt | wc -l
grep Inv chr24/non_commons_fromAll.txt | wc -l
grep Inv chr25/non_commons_fromAll.txt | wc -l
