cd $1
echo "Commons:"
grep Inv chr1/final_bir_locs.txt | wc -l
grep Inv chr2/final_bir_locs.txt | wc -l
grep Inv chr3/final_bir_locs.txt | wc -l
grep Inv chr4/final_bir_locs.txt | wc -l
grep Inv chr5/final_bir_locs.txt | wc -l
grep Inv chr6/final_bir_locs.txt | wc -l
grep Inv chr7/final_bir_locs.txt | wc -l
grep Inv chr8/final_bir_locs.txt | wc -l
grep Inv chr9/final_bir_locs.txt | wc -l
grep Inv chr10/final_bir_locs.txt | wc -l
grep Inv chr11/final_bir_locs.txt | wc -l
grep Inv chr12/final_bir_locs.txt | wc -l
grep Inv chr13/final_bir_locs.txt | wc -l
grep Inv chr14/final_bir_locs.txt | wc -l
grep Inv chr15/final_bir_locs.txt | wc -l
grep Inv chr16/final_bir_locs.txt | wc -l
grep Inv chr17/final_bir_locs.txt | wc -l
grep Inv chr18/final_bir_locs.txt | wc -l
grep Inv chr19/final_bir_locs.txt | wc -l
grep Inv chr20/final_bir_locs.txt | wc -l
grep Inv chr21/final_bir_locs.txt | wc -l
grep Inv chr22/final_bir_locs.txt | wc -l
grep Inv chr23/final_bir_locs.txt | wc -l
grep Inv chr24/final_bir_locs.txt | wc -l
grep Inv chr25/final_bir_locs.txt | wc -l

echo "Non-Commons:"
grep Inv chr1/final_bir_locs.txt | wc -l
grep Inv chr2/final_bir_locs.txt | wc -l
grep Inv chr3/final_bir_locs.txt | wc -l
grep Inv chr4/final_bir_locs.txt | wc -l
grep Inv chr5/final_bir_locs.txt | wc -l
grep Inv chr6/final_bir_locs.txt | wc -l
grep Inv chr7/final_bir_locs.txt | wc -l
grep Inv chr8/final_bir_locs.txt | wc -l
grep Inv chr9/final_bir_locs.txt | wc -l
grep Inv chr10/final_bir_locs.txt | wc -l
grep Inv chr11/final_bir_locs.txt | wc -l
grep Inv chr12/final_bir_locs.txt | wc -l
grep Inv chr13/final_bir_locs.txt | wc -l
grep Inv chr14/final_bir_locs.txt | wc -l
grep Inv chr15/final_bir_locs.txt | wc -l
grep Inv chr16/final_bir_locs.txt | wc -l
grep Inv chr17/final_bir_locs.txt | wc -l
grep Inv chr18/final_bir_locs.txt | wc -l
grep Inv chr19/final_bir_locs.txt | wc -l
grep Inv chr20/final_bir_locs.txt | wc -l
grep Inv chr21/final_bir_locs.txt | wc -l
grep Inv chr22/final_bir_locs.txt | wc -l
grep Inv chr23/final_bir_locs.txt | wc -l
grep Inv chr24/final_bir_locs.txt | wc -l
grep Inv chr25/final_bir_locs.txt | wc -l
